### ISSUE TITLE
problema integraziopne

### ISSUE THREAD

**Issue by Alfafoxred** [Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice#2]
Ciao, volevo integralo sul mio Home Assistant ma non riesco, copio il HTTPS vado su HACS poi Repository personalizzati e incollo mi esce il seguente errore <Integration Home-Assistant-Pro-Team/Gestione-Allarme-Home-Assistant-Alarm> Repository structure for main is not compliant.
Ho provato anche con le altre integrazioni di Home Assistant Pro Team e mi da lo stesso errore.
Cosa sbaglio devo eseguire ina procedura differente per integrare il tutto?

**Comment by marco-hacs** [comment]
Nel readmi è descritto come si monta il pkg ed i requisiti. Stai trattando questo lavoro come fosse un custom di hacs cosa completamente errata.

**Comment by Alfafoxred** [comment]
ok ho visto trovato le istruzioni perfetto ti ringrazio
