### ISSUE TITLE
Pop ups

### ISSUE THREAD

**Issue by RaRo1980** [Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice#3]
Hello, i tryed this mart-Laundry System, so it is running but the pop up on the cards are not working
what can be the reason.
![grafik](https://github.com/Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice/assets/66684606/7561cce1-7044-4ca6-9a6f-41e8f623cb9f)

**Comment by marco-hacs** [comment]
you must have installed and added browser mode as per the guide
