### ISSUE TITLE
Ritardo anche oper spegnimento

### ISSUE THREAD

**Issue by MikZenn** [Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice#4]
Buongiorno,

sarebbe utile un ritardo non solo per l'accensione, ma anche per lo spegnimento.
Nel senso che se la presa si trova per tot tempo ad un certo livello di potenza, sarebbe bene venga considerata spenta (fine lavaggio più precisamente).

Capita spesso le prese abbiano un delay piuttosto importante prima di anadre veramente a zero come consumo rilevato.

Ho provato a guradare il codice, ma essendo scritto in una forma molto avanzata per me ( complimenti per la pulizia e la stesura) non sono in grado di capire dove inserire tale delay.

Esempio: se segna 3W per 2 minuti considerarla come spenta/fine lavaggio.

**Comment by marco-hacs** [comment]
Il ritardo che imposti dalla card è già per lo spegnimento. 
In pratica imposti i watt sopra i quali deve considerare accesa la lavatrice.
Mentre per rilevare la lavatrice spenta imposti i minuti dopo il quale l'assorbimento scende sotto la soglia impostata. 
![image](https://github.com/Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice/assets/62516592/6017b147-fea9-4fc0-ac7d-985a3d58c25a)

In pratica non c'è nessun ritardo in accenzione ma solo in spegnimento. 
![image](https://github.com/Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice/assets/62516592/a9c122ba-87c8-47c5-8089-520304d06872)
