### ISSUE TITLE
card markdown does not work 

### ISSUE THREAD

**Issue by sideAgo** [Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice#6]
card markdown does not work 
Static is no longer displayed with the latest Home Assistant update, because the card content no longer accepts programming statements such as set and if

**Comment by marco-hacs** [comment]
has been updated the package and fixed the card issue... you can decide whether to upload only the card with the fix or the whole new one which includes small improvements. 

Thanks for the report

**Comment by sideAgo** [comment]
Thank you

Il Mer 10 Lug 2024, 01:10 Marco ***@***.***> ha scritto:

**Comment by sideAgo** [comment]
Buon pomeriggio
grazie per l'aggiornamento perchè ha risolto il problema del sensore non
disponibile.

Resta comunque presente il problema che avevo segnalato, la pagina di
statistica markdown è vuota al contrario delle altre due (manutenzione ed
impostazioni).
Il problema è dovuto alle istruzioni di programmazione presenti sotto il
content (set, if, for...). Difatti le altre non hanno questo tipo di
istruzioni e senza questo popup funziona normalmente.

Grazie

Il giorno mer 10 lug 2024 alle ore 10:44 Luca Agozzino <
***@***.***> ha scritto:

**Comment by sideAgo** [comment]
Utilizzando la card con le nuove modifiche inoltre ho notato che non
compare più il toggle di ritirare i panni e non funzionano le notifiche in
generale (app e alexa)

Il giorno gio 11 lug 2024 alle ore 15:08 Luca Agozzino <
***@***.***> ha scritto:
